[package]
name = "omicron-zone-package"
version = "0.3.2"
authors = ["Sean Klein <sean@oxidecomputer.com>"]
edition = "2018"
license = "MPL-2.0"
repository = "https://github.com/oxidecomputer/omicron-package"
description = "Packaging tools for Oxide's control plane software"

[dependencies]
anyhow = "1.0"
chrono = "0.4.19"
filetime = "0.2.16"
flate2 = "1.0.22"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
serde = { version = "1.0", features = [ "derive" ] }
serde_derive = "1.0"
tar = "0.4"
tempfile = "3.3"
thiserror = "1.0"
tokio = { version = "1.17", features = [ "full" ] }
toml = "0.5.8"
walkdir = "2.3"
